FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source code
COPY . .

EXPOSE 5173

# Start dev server on port 5173 exposing to all network interfaces
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
